/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ross.mvc.view;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author rafael
 */
public class DefaultWindow extends JFrame {

    /**
     * Creates new form DefaultWindow
     */
    public DefaultWindow() {
        
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        
        themes = UIManager.getInstalledLookAndFeels();
        
    try{
            //UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro na aplicação do thema");
            
        }        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        menuItemChangeComp = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemEmployees = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Default Window");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("Form"); // NOI18N

        dtp.setName("dtp"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu7.setMnemonic('S');
        jMenu7.setText("Sistema");
        jMenu7.setName("jMenu7"); // NOI18N

        menuItemChangeComp.setText("Selecionar Empresa...");
        menuItemChangeComp.setName("menuItemChangeComp"); // NOI18N
        jMenu7.add(menuItemChangeComp);

        menuItemExit.setMnemonic('S');
        menuItemExit.setText("Sair");
        menuItemExit.setName("menuItemExit"); // NOI18N
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemExit);

        jMenuBar1.add(jMenu7);

        jMenu1.setMnemonic('C');
        jMenu1.setText("Cadastros");
        jMenu1.setName("jMenu1"); // NOI18N

        menuItemEmployees.setText("Funcionários");
        menuItemEmployees.setName("menuItemEmployees"); // NOI18N
        menuItemEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmployeesActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemEmployees);

        jMenuItem3.setText("Eventos");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Seções");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Sindicatos");
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenu1.add(jMenuItem5);

        jMenu11.setText("Cargos/Funções");
        jMenu11.setName("jMenu11"); // NOI18N

        jMenuItem6.setText("Cargos");
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenu11.add(jMenuItem6);

        jMenuItem7.setText("Funções");
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenu11.add(jMenuItem7);

        jMenu1.add(jMenu11);

        jMenu12.setText("Cálculos");
        jMenu12.setName("jMenu12"); // NOI18N

        jMenuItem8.setText("Valores Fixos");
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        jMenu12.add(jMenuItem8);

        jMenuItem9.setText("Tabelas de Cálculo");
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenu12.add(jMenuItem9);

        jMenu1.add(jMenu12);

        jMenu13.setText("Tabelas Auxiliares");
        jMenu13.setName("jMenu13"); // NOI18N

        jMenuItem10.setText("Horários");
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        jMenu13.add(jMenuItem10);

        jMenuItem11.setText("Linhas de Transporte");
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        jMenu13.add(jMenuItem11);

        jMenuItem12.setText("Tarifas de Transporte");
        jMenuItem12.setName("jMenuItem12"); // NOI18N
        jMenu13.add(jMenuItem12);

        jMenu1.add(jMenu13);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('M');
        jMenu2.setText("Movimento");
        jMenu2.setName("jMenu2"); // NOI18N

        jMenu8.setText("Folha de Pagamento");
        jMenu8.setName("jMenu8"); // NOI18N
        jMenu2.add(jMenu8);

        jMenu9.setText("Férias");
        jMenu9.setName("jMenu9"); // NOI18N
        jMenu2.add(jMenu9);

        jMenu10.setText("13º Salário");
        jMenu10.setName("jMenu10"); // NOI18N
        jMenu2.add(jMenu10);

        jMenu14.setText("Rescisão");
        jMenu14.setName("jMenu14"); // NOI18N
        jMenu2.add(jMenu14);

        jMenuBar1.add(jMenu2);

        jMenu4.setMnemonic('T');
        jMenu4.setText("Rotinas");
        jMenu4.setName("jMenu4"); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('R');
        jMenu5.setText("Relatórios");
        jMenu5.setName("jMenu5"); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu6.setMnemonic('O');
        jMenu6.setText("Opções");
        jMenu6.setName("jMenu6"); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu3.setMnemonic('U');
        jMenu3.setText("Utilitários");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu15.setMnemonic('J');
        jMenu15.setText("Janelas");
        jMenu15.setName("jMenu15"); // NOI18N
        jMenuBar1.add(jMenu15);

        jMenu16.setMnemonic('A');
        jMenu16.setText("Ajuda");
        jMenu16.setName("jMenu16"); // NOI18N
        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmployeesActionPerformed
        DefaultInternalWindow intWindow = new DefaultInternalWindow();
        
        
        
        intWindow.setTitle(menuItemEmployees.getText());
        intWindow.setSize(this.getSize());
        intWindow.criaJanela();
        dtp.add(intWindow);
        intWindow.setVisible(true);
        
    }//GEN-LAST:event_menuItemEmployeesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefaultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefaultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefaultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefaultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaultWindow().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuItemChangeComp;
    private javax.swing.JMenuItem menuItemEmployees;
    private javax.swing.JMenuItem menuItemExit;
    // End of variables declaration//GEN-END:variables
    private UIManager.LookAndFeelInfo themes[];
}
